# Generated by Django 2.1.5 on 2019-01-22 17:16

from django.db import migrations, models
import django.db.models.deletion
import source.CDR


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdPatient',
            fields=[
                ('PersonID', models.BigAutoField(primary_key=True, serialize=False)),
                ('SSNumber', models.CharField(blank=True, max_length=11, null=True)),
                ('FirstName', models.CharField(blank=True, max_length=85, null=True)),
                ('MiddleInitial', models.CharField(blank=True, max_length=1, null=True)),
                ('LastName', models.CharField(blank=True, max_length=60, null=True)),
                ('Address1', models.CharField(blank=True, max_length=60, null=True)),
                ('Address2', models.CharField(blank=True, max_length=60, null=True)),
                ('Address3', models.CharField(blank=True, max_length=60, null=True)),
                ('City', models.CharField(blank=True, max_length=60, null=True)),
                ('StateProv', models.CharField(blank=True, max_length=4, null=True)),
                ('PostalCode', models.CharField(blank=True, max_length=10, null=True)),
                ('Country', models.CharField(blank=True, max_length=60, null=True)),
                ('Language', models.CharField(blank=True, max_length=60, null=True)),
                ('Email', models.CharField(blank=True, max_length=60, null=True)),
                ('Homephone', models.CharField(blank=True, max_length=12, null=True)),
                ('Cellphone', models.CharField(blank=True, max_length=12, null=True)),
                ('RelationReference', models.CharField(blank=True, max_length=24, null=True)),
                ('Active', models.BooleanField(default=True)),
                ('Sex', models.CharField(blank=True, max_length=1, null=True)),
                ('Race', models.CharField(blank=True, max_length=16, null=True)),
                ('DateOfBirth', models.DateField(blank=True, null=True)),
                ('Age', models.PositiveIntegerField(blank=True, null=True)),
                ('ShipCode', models.IntegerField(blank=True, null=True)),
                ('custparent', source.CDR.SpanningForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='portal.Custparent')),
            ],
            options={
                'db_table': 'id_patient',
            },
        ),
        migrations.CreateModel(
            name='IdPatientAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MedicalRecordID', models.CharField(blank=True, max_length=60, null=True)),
                ('InternalPatientReference', models.CharField(blank=True, max_length=60, null=True)),
                ('AdmitDate', models.DateField(blank=True, null=True)),
                ('DischargeDate', models.DateField(blank=True, null=True)),
                ('BillingMethod', models.CharField(blank=True, max_length=60, null=True)),
                ('Payor', models.CharField(blank=True, max_length=120, null=True)),
                ('InsuranceID', models.CharField(blank=True, max_length=60, null=True)),
                ('MedicareID', models.CharField(blank=True, max_length=60, null=True)),
                ('MedicaidID', models.CharField(blank=True, max_length=60, null=True)),
                ('LocationID', models.BigIntegerField(blank=True, null=True)),
                ('Room', models.CharField(blank=True, max_length=60, null=True)),
                ('Bed', models.CharField(blank=True, max_length=60, null=True)),
                ('PriceGroup', models.CharField(blank=True, max_length=60, null=True)),
                ('Level', models.CharField(blank=True, max_length=12, null=True)),
                ('InContinenceSize', models.CharField(blank=True, max_length=25, null=True)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.IdPatient')),
            ],
            options={
                'db_table': 'id_patient_attr',
            },
        ),
    ]
