# Generated by Django 2.1.5 on 2019-01-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargessupply',
            name='Quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
