# Generated by Django 2.1.5 on 2019-01-22 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import source.CDR
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('jwt_secret', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custparent', source.CDR.SpanningForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to='portal.Custparent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'relation',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='custparent',
            field=models.ManyToManyField(related_name='facility', through='users.Relation', to='portal.Custparent'),
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('user', 'custparent')},
        ),
    ]
